In [1]:
import pandas as pd

df = pd.read_csv("deepswe_20260709 - Sheet1.csv")
df

,gpt-5.6-sol[max],gpt-5.6-sol[xhigh],claude-fable-5[xhigh],claude-fable-5[max],gpt-5.6-terra[max],gpt-5.6-sol[high],claude-fable-5[high],gpt-5.6-luna[max],gpt-5.5[xhigh],claude-fable-5[medium],...,claude-sonnet-5[high],gpt-5.6-sol[low],gpt-5.6-luna[high],glm-5.2[max],claude-opus-4.8[low],claude-sonnet-5[medium],gemini-3.5-flash[medium],glm-5.2[high],gpt-5.6-terra[medium],kimi-k2.7-code
0,73%±3%,71%±1%,70%±3%,70%±4%,70%±3%,69%±1%,69%±1%,67%±4%,67%±6%,65%±4%,...,48%±5%,45%±2%,44%±3%,44%±2%,41%±1%,40%±3%,37%±2%,36%±5%,35%±3%,31%±1%
1,$8.39,$4.70,$13.41,$21.63,$4.95,$3.47,$9.18,$3.03,$7.23,$6.09,...,$7.43,$1.07,$0.78,$3.92,$2.29,$4.08,$7.34,$2.84,$0.58,$2.82
2,60k,41k,80k,119k,72k,28k,57k,73k,46k,40k,...,87k,11k,26k,78k,29k,57k,276k,54k,12k,59k
3,61,44,68,88,76,37,59,102,82,48,...,147,23,49,129,54,108,86,122,25,149

In [19]:
# transform the data frame so the columns become rows and the rows become columns
df_transposed = df.T
# reset the index
df_transposed.reset_index(inplace=True)
# add column names ["model", "score", "cost", "out_tokens", "steps"]
df_transposed.columns = ["model", "score", "cost", "out_tokens", "steps"]

# split the "score" column on the +- symbol and move the second % to a new column "variance"
df_transposed[["score", "variance"]] = df_transposed["score"].str.split("±", expand=True)

# in "score" and "variance", strip the "%" symbol and make it an integer. In "cost" column, strip the $ symbol and make it a float.
df_transposed["score"] = df_transposed["score"].str.rstrip("%").astype(int)
df_transposed["variance"] = df_transposed["variance"].str.rstrip("%").astype(int)
df_transposed["cost"] = df_transposed["cost"].str.lstrip("$").astype(float)
df_transposed["out_tokens"] = df_transposed["out_tokens"].str.rstrip("k").astype(int)

# reorder the df columns by ["model", "score", "variance", "cost", "out_tokens", "steps"]
df_transposed = df_transposed[["model", "score", "variance", "cost", "out_tokens", "steps"]]

# set "model" as the index
df_transposed.set_index("model", inplace=True)

df_transposed

                          score  variance   cost  out_tokens steps
model
gpt-5.6-sol[max]             73         3   8.39          60    61
gpt-5.6-sol[xhigh]           71         1   4.70          41    44
claude-fable-5[xhigh]        70         3  13.41          80    68
claude-fable-5[max]          70         4  21.63         119    88
gpt-5.6-terra[max]           70         3   4.95          72    76
gpt-5.6-sol[high]            69         1   3.47          28    37
claude-fable-5[high]         69         1   9.18          57    59
gpt-5.6-luna[max]            67         4   3.03          73   102
gpt-5.5[xhigh]               67         6   7.23          46    82
claude-fable-5[medium]       65         4   6.09          40    48
gpt-5.5[high]                64         3   5.10          31    62
gpt-5.6-sol[medium]          61         2   1.86          18    31
gpt-5.6-terra[xhigh]         60         2   2.13          40    43
claude-fable-5[low]          60         3   3.76          25    38
claude-opus-4.8[max]         59         2  13.22         135   120
gpt-5.6-luna[xhigh]          57         2   1.54          45    71
claude-opus-4.8[xhigh]       54         4   8.01          86    95
gpt-5.5[medium]              54         3   2.75          20    46
claude-sonnet-5[max]         54         4  26.40         214   268
gpt-5.6-terra[high]          54         4   1.13          22    34
claude-opus-4.8[high]        52         5   4.28          50    73
gpt-5.4[xhigh]               52         2   5.65          71    70
claude-sonnet-5[xhigh]       50         3  11.89         121   186
claude-opus-4.8[medium]      49         2   3.44          41    66
claude-sonnet-5[high]        48         5   7.43          87   147
gpt-5.6-sol[low]             45         2   1.07          11    23
gpt-5.6-luna[high]           44         3   0.78          26    49
glm-5.2[max]                 44         2   3.92          78   129
claude-opus-4.8[low]         41         1   2.29          29    54
claude-sonnet-5[medium]      40         3   4.08          57   108
gemini-3.5-flash[medium]     37         2   7.34         276    86
glm-5.2[high]                36         5   2.84          54   122
gpt-5.6-terra[medium]        35         3   0.58          12    25
kimi-k2.7-code               31         1   2.82          59   149

In [20]:
# add a visual bar that starts from the left edge of the cell
df_transposed["visual_score"] = df_transposed["score"].apply(lambda x: "█" * (x // 2)).str.ljust(60, " ")

styled_df = (
    df_transposed.style
    .set_properties(subset=["visual_score"], **{"text-align": "left"})
    .set_table_styles(
        [
            {"selector": "th", "props": [("text-align", "left")]},
            {"selector": "td", "props": [("text-align", "left")]},
        ]
    )
)

styled_df

In [21]:
df_cost = df_transposed.sort_values("cost")

styled_df = (
    df_cost.style
    .set_properties(subset=["visual_score"], **{"text-align": "left"})
    .set_table_styles(
        [
            {"selector": "th", "props": [("text-align", "left")]},
            {"selector": "td", "props": [("text-align", "left")]},
        ]
    )
)

styled_df

In [22]:
df_variance = df_transposed.sort_values("variance")

styled_df = (
    df_variance.style
    .set_properties(subset=["visual_score"], **{"text-align": "left"})
    .set_table_styles(
        [
            {"selector": "th", "props": [("text-align", "left")]},
            {"selector": "td", "props": [("text-align", "left")]},
        ]
    )
)

styled_df